[package]
name = "rust-flake"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
cloudflare = "0.11.0"
serde = "1.0"
serde_yaml = "0.9"
